export function generateSummary({ modality, score, verdict, emoji, language, flags }) {
  const timestamp = new Date().toLocaleString();
  return `TruthGuard Analysis — ${modality.toUpperCase()}
─────────────────────────────
Trust Score: ${score}/100
Verdict: ${verdict} ${emoji}
Language: ${language}
─────────────────────────────
Issues Detected:
${flags?.length ? flags.map(f => "• " + f).join("\n") : "• None"}
─────────────────────────────
Analyzed on: ${timestamp}
Powered by TruthGuard — CodeWizards 2.0`;
}

export function generateShareLink({ modality, score, verdict, language, flags }) {
  try {
    const payload = JSON.stringify({ score, verdict, modality, language, flags });
    const encoded = btoa(unescape(encodeURIComponent(payload)));
    return `${window.location.origin}?result=${encoded}`;
  } catch (err) {
    console.error("Failed to generate share link", err);
    return window.location.origin;
  }
}

export function downloadReport({ modality, score, verdict, emoji, language, flags, explanation, sources }) {
  const timestamp = new Date().toLocaleString();
  const fileTimestamp = new Date().toISOString().replace(/[:.]/g, '-');
  
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TruthGuard Analysis Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px 20px; background: #f8fafc; }
        .header { background: #0f172a; color: white; padding: 30px; border-radius: 16px 16px 0 0; text-align: center; }
        .content { background: white; padding: 40px; border-radius: 0 0 16px 16px; shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }
        .score-box { display: flex; align-items: center; justify-content: space-between; margin-bottom: 30px; padding: 20px; background: #f1f5f9; border-radius: 12px; }
        .score { font-family: monospace; font-size: 48px; font-weight: bold; color: #2563eb; }
        .verdict { font-size: 24px; font-weight: bold; text-transform: uppercase; }
        .section-title { font-size: 18px; font-weight: bold; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px; margin-bottom: 16px; color: #1e293b; }
        .flag-item { margin-bottom: 8px; padding-left: 12px; border-left: 3px solid #ef4444; }
        .source-item { margin-bottom: 12px; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #64748b; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ TruthGuard Analysis Report</h1>
        <p>${modality.toUpperCase()} Analysis · ${timestamp}</p>
    </div>
    <div class="content">
        <div class="score-box">
            <div>
                <div style="font-size: 12px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 1px;">Trust Score</div>
                <div class="score">${score}/100</div>
            </div>
            <div style="text-align: right;">
                <div style="font-size: 12px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 1px;">Verdict</div>
                <div class="verdict" style="color: ${score >= 70 ? '#16a34a' : score >= 40 ? '#d97706' : '#dc2626'}">${verdict} ${emoji}</div>
            </div>
        </div>

        <div class="section-title">Analysis Context</div>
        <p><strong>Language:</strong> ${language}</p>
        
        ${flags?.length ? `
            <div class="section-title">Issues Detected</div>
            ${flags.map(f => `<div class="flag-item">${f}</div>`).join('')}
        ` : ''}

        ${explanation ? `
            <div class="section-title">AI Explanation</div>
            <div style="white-space: pre-line;">${explanation}</div>
        ` : ''}

        ${sources?.length ? `
            <div class="section-title">Verified Alternative Sources</div>
            ${sources.map(s => `
                <div class="source-item">
                    <div style="font-weight: bold;">${s.title}</div>
                    <div style="font-size: 12px; color: #64748b;">Source: ${s.source}</div>
                </div>
            `).join('')}
        ` : ''}

        <div class="footer">
            <p>Report generated by TruthGuard — AI Against Misinformation</p>
            <p>© 2024 CodeWizards 2.0</p>
        </div>
    </div>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `truthguard-${modality}-report-${fileTimestamp}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
